sudo : required
services: 
  - docker

before_install:
  - docker build -t marlanfer/react-test -f ./client/Dockerfile.dev ./client

scripts: 
  - docker run -e CI=true marlanfer/react-test npm test

after_success: 
  - docker build -t marlanfer/multi-client ./client
  - docker build -t marlanfer/multi-nginx ./nginx
  - docker build -t marlanfer/multi-server ./server
  - docker build -t marlanfer/multi-worker ./worker
  # docker logn
  - echo "$DOCKER_PW" | docker login -u "$DOCKER_ID" --password-stdin
  # docker push
  - docker push marlanfer/multi-client
  - docker push marlanfer/multi-nginx
  - docker push marlanfer/multi-server
  - docker push marlanfer/multi-worker

deploy:
  provider: elasticbeanstalk
  region: 'us-east-1'
  app: 'docker-mr'
  env: 'Dockermr-env'
  bucket_name: 'elasticbeanstalk-us-east-1-822437909896'
  bucket_path: 'docker-multi'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
