sudo : required
services: 
  - docker

before_install:
  - docker build -t marlanfer/react-test -f ./client/Dockerfile.dev ./client

scripts: 
  - - docker run -e CI=true marlanfer/react-test npm test

after_success: 
  - docker build -t marlanfer/multi-client ./client
  - docker build -t marlanfer/multi-nginx ./nginx
  - docker build -t marlanfer/multi-server ./server
  - docker build -t marlanfer/multi-worker ./worker


